name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: test (Erlang/OTP ${{matrix.otp}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
        otp: [25.x, 24.x, 23.x]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libzmq3-dev
      - name: Build
        run: rebar3 compile
      - name: Test
        run: rebar3 eunit
      - name: Build docs
        run: rebar3 edoc
