name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: test (Erlang/OTP ${{matrix.otp}}, ${{matrix.os}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 26.x
            rebar3: 3.22.0
            os: ubuntu-22.04
          - otp: 25.x
            rebar3: 3.20.0
            os: ubuntu-22.04
          - otp: 24.x
            rebar3: 3.20.0
            os: ubuntu-20.04
          - otp: 23.x
            rebar3: 3.20.0
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          install-rebar3: true
          rebar3-version: ${{matrix.rebar3}}
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libzmq3-dev
      - name: Build
        run: rebar3 compile
      - name: Test
        run: rebar3 eunit
      - name: Build docs
        run: rebar3 edoc
